from dataclasses import dataclass

"""
Data class for storing video subtitles
"""
@dataclass
class Subtitles:
        subtitles: list[dict[str, str]]
        autogenerated_subtitles: list[dict[str, str]]