"""
Video subtitles
"""
from dataclasses import dataclass

@dataclass
class Subtitles:
    """Data class for storing subtitles"""
    subtitles: list[dict[str, str]]
    autogenerated_subtitles: list[dict[str, str]]
