"""
Util for processing subtitles
"""
import re
from typing import Optional

from src.core.config.config import START_TABLE_AUTOGENERATED_SUBS, START_TABLE_SUBS, START_TABLE_FORMATS
from src.core.dataclass.subtitle import Subtitles

_WHITESPACE_GROUP_RE = re.compile(r'\s{2,}')


def subtitles_parse_output(subtitles_str: list[str]) -> Subtitles:
    """Parse the yt-dlp output to extract two subtitle lists:"""
    autogenerated_subtitles = _get_subtitles(subtitles_str, START_TABLE_AUTOGENERATED_SUBS, [START_TABLE_SUBS, START_TABLE_FORMATS])
    available_subtitles = _get_subtitles(subtitles_str, START_TABLE_SUBS, [START_TABLE_AUTOGENERATED_SUBS, START_TABLE_FORMATS])

    return Subtitles(available_subtitles,autogenerated_subtitles)

def _get_subtitles(subtitles_str: list[str], prefix: str = "", end_of_table: Optional[list[str]] = None) -> list[dict[str, str]]:
    """Extract subtitle entries that appear after a given section prefix."""
    subs: list[dict[str, str]] = []
    in_table = False

    for line in subtitles_str:
        if not isinstance(line, str):
            continue

        if line.startswith(prefix) and len(line) > len(prefix):
            in_table = True
            continue

        if end_of_table and in_table:
            for line_end_of_table in end_of_table:
                if line.startswith(line_end_of_table) and len(line) > len(line_end_of_table):
                    in_table = False
            if not in_table:
                break

        if not in_table:
            continue

        if line.strip().startswith("Language"):
            continue

        if not line.strip():
            break

        parts = _WHITESPACE_GROUP_RE.split(line.strip())

        if len(parts) < 3:
            continue

        language = parts[0]
        name = parts[1]
        formats_raw = parts[2]

        formats = " ".join(f.strip() for f in formats_raw.split(",") if f.strip())

        subs.append({
            "Language": language,
            "Name": name.strip(),
            "Formats": formats
        })

    return subs
