"""
Global config
"""
import os
import sys


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
YT_DLP_PATH: str = "yt-dlp.exe" if sys.platform == "win32" else "yt-dlp"
TIMEOUT: int = 300
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
LOG_DIR = os.path.join(PROJECT_ROOT, "logs")
START_TABLE_SUBS="[info] Available subtitles for "
START_TABLE_AUTOGENERATED_SUBS="[info] Available automatic captions for "
START_TABLE_FORMATS="[info] Available formats for "
API_TOKEN = "AIzaSyCxLEQjVa76qtd_bm-_CxU08gbdv-GVv-E"
